# Docker Image
image: vuejs/ci

# 環境変数 (Web画面から設定も可能)
variables:
  FIREBASE_PROJECT_ID: xxxxxxx
  FIREBASE_TOKEN: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# アーティファクト内で共有するディレクトリの設定
cache:
  paths:
    - node_modules/
    - dist/

# jobの処理順を指定
stages:
  - init
  - ci
  - cd

init: # job名
  stage: init # stagesで使用する名前 他のjobに同じ名前をつけることで並列処理になる
  artifacts: # 前回生成されたアーティファクトから引き継ぐディレクトリを指定
    paths:
      - node_modules/
  script: # ここにメインの処理を書く
    - yarn
  only: # 実行するタイミングを指定
    - master
    - merge_requests

test:
  stage: ci
  script:
    - yarn unit
  only:
    - master
    - merge_requests

build:
  stage: ci
  script:
    - yarn build
  only:
    - master
    - merge_requests

deploy:
  stage: cd
  script:
    - yarn add firebase-tools
    - node_modules/firebase-tools/lib/bin/firebase.js use $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
    - node_modules/firebase-tools/lib/bin/firebase.js deploy --token $FIREBASE_TOKEN
  only:
    - master
