# Docker Image
image: vuejs/ci

# 環境変数 (Web画面から設定も可能)
.set_environment: &setenv |
  export FIREBASE_PROJECT_ID=xxxxxxx
  export FIREBASE_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

# 定義
definitions:
  steps:
    - step: &init # *initと書くことでこの処理を呼び出せる
        name: init
        caches: # 前回生成されたアーティファクトから引き継ぐディレクトリを指定
          - node
        script: # ここにメインの処理を書く
          - yarn
        artifacts: # アーティファクト内で共有するディレクトリの設定
          - node_modules/**
    - parallel: &ci # parallelに複数stepを書くことで並列処理になる
        - step:
            name: Test
            script:
              - yarn unit
        - step:
            name: Build
            script:
              - yarn build
            artifacts: # アーティファクト内で共有するディレクトリの設定
              - dist/**

pipelines:
  pull-requests: # プルリク時の処理
    '**': # 全てのプルリク feature/*: などブランチを指定できる
      - step: *init
      - parallel: *ci
  branches:
    master: # masterにコミットされた時の処理
      - step: *init
      - parallel: *ci
      - step:
          name: Deploy
          script:
            - *setenv # 環境設定読み込み
            - yarn add firebase-tools
            - node_modules/firebase-tools/lib/bin/firebase.js use $FIREBASE_PROJECT_ID --token $FIREBASE_TOKEN
            - node_modules/firebase-tools/lib/bin/firebase.js deploy --token $FIREBASE_TOKEN
